apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-weekly-backup
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "30 6 * * 0" # Run every Sunday at 6:30 AM
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            azure.workload.identity/use: 'true'
          annotations:
            checksum/secret_env: {{ include (print $.Template.BasePath "/secret_env.yaml") . | sha256sum }}
        spec:
          serviceAccountName: {{ .Values.serviceAccountName }}
          containers:
          - name: {{ .Release.Name }}
            image: {{ .Values.image }}
            env:
              - name: TASK
                value: "backup"
              - name: RETENTION_PERIOD
                value: "30"
            envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          restartPolicy: Never
