apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 7 2-31 * *" # At 07:00 on every day-of-month from 2 through 31.
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: 'true'
          annotations:
            checksum/secret_env: {{ include (print $.Template.BasePath "/secret_env.yaml") . | sha256sum }}
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: curlimage
            image: curlimages/curl:latest
            command:
                - /bin/sh
                - -c
                - |
                  set -e
                  AZURE_FEDERATED_TOKEN=$(cat $AZURE_FEDERATED_TOKEN_FILE)
                  # Get an access token from Entra ID
                  ACCESS_TOKEN=$(curl -s -X POST "https://login.microsoftonline.com/$(AZURE_TENANT_ID)/oauth2/v2.0/token" \
                    -H "Content-Type: application/x-www-form-urlencoded" \
                    -d "client_id=$(AZURE_CLIENT_ID)" \
                    -d "client_secret=$(AZURE_FEDERATED_TOKEN)" \
                    -d "scope=$(API_CLIENT_ID)/createBackup" \
                    -d "scope=$(API_CLIENT_ID)/cleanupBackups" \
                    -d "grant_type=client_credentials")

                  # Trigger backup
                  curl -X POST postgres-azure-backup:8080/api/backup?retention_period=1 --fail \
                    -H "Authorization: Bearer $ACCESS_TOKEN" \
                    -H "Content-Type: application/json"
            envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          restartPolicy: Never
