blobstorage:
  endpoint: ${BLOBSTORAGE_ENDPOINT_URL:}
  connectionString: ${BLOBSTORAGE_CONNECTION_STRING:}

databasesConfigPath: ${DATABASES_CONFIG_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jwk-set-uri: ${AUTH_JWK_SET_URI}
