blobstorage:
  endpoint: ${BLOBSTORAGE_ENDPOINT_URL:}
  connectionString: ${BLOBSTORAGE_CONNECTION_STRING:}

databasesConfigPath: ${DATABASES_CONFIG_PATH}

management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
